version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: itunes_library
      POSTGRES_USER: itunes_user
      POSTGRES_PASSWORD: itunes_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6380:6379"

  web:
    build: .
    command: uvicorn src.itunes_library_manager.api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=itunes_library
      - DB_USER=itunes_user
      - DB_PASSWORD=itunes_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A src.itunes_library_manager.tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=itunes_library
      - DB_USER=itunes_user
      - DB_PASSWORD=itunes_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - db
      - redis

  frontend:
    image: nginx:alpine
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  postgres_data: